### LOCALHOST 

### Get all profiles
GET http://localhost:3000/profiles

### Get profile by id
GET http://localhost:3000/profiles/62871171ad3a5374a92f8aa9

### Create a new profile
POST http://localhost:3000/profiles HTTP/1.1
content-type: application/json

{
    "userName":"NewerProfile",
    "password":"newProfPass",
    "email":"newProfile@test.com"
}

### Delete a profile
DELETE http://localhost:3000/profiles/628d4918eac73b481c8f76a7

### Update a profile
PUT http://localhost:3000/profiles/628d4918eac73b481c8f76a7 HTTP/1.1
content-type: application/json

{
    "userName":"NewerProfile",
    "password":"newProfPass",
    "email":"newProfile@test.com"
}

### Get all exercises
GET http://localhost:3000/exercises

### Get exercise by id
GET http://localhost:3000/exercises/628d436adb3d9e3cba6a1792

### Create a new exercise
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "name":"Run Around the Block",
    "description":"Run around the block near our apartment.",
    "images":[],
    "videos":[],
    "tags":["cardio", "no-weight"],
    "user_id": "62871171ad3a5374a92f8aa9"
}


### Delete an exercise
DELETE http://localhost:3000/exercises/628d436adb3d9e3cba6a1792

### Update an exercise
PUT http://localhost:3000/exercises/628d505e82b99c3474e6c474 HTTP/1.1
content-type: application/json

{
    "name":"Run Around the Block",
    "description":"Run around the block near our apartment.",
    "images":[],
    "videos":[],
    "tags":["cardio"],
    "user_id": "62871171ad3a5374a92f8aa9"
}




### HEROKU

### Get all profiles
GET https://tubular-backend.herokuapp.com/profiles

### Get profile by id
GET https://tubular-backend.herokuapp.com/profiles/62871171ad3a5374a92f8aa9

### Create a new profile
POST https://tubular-backend.herokuapp.com/profiles HTTP/1.1
content-type: application/json

{
    "userName":"NewerProfile",
    "password":"newProfPass",
    "email":"newProfile@test.com"
}

### Get all exercises
GET https://tubular-backend.herokuapp.com/exercises

### Get exercise by id
GET https://tubular-backend.herokuapp.com/exercises/628d436adb3d9e3cba6a1792

### Create a new exercise
POST https://tubular-backend.herokuapp.com/exercises HTTP/1.1
content-type: application/json

{
    "name":"Run Around the Block",
    "description":"Run around the block near our apartment.",
    "images":[],
    "videos":[],
    "tags":["cardio", "no-weight"],
    "user_id": "62871171ad3a5374a92f8aa9"
}

### Delete an exercise
DELETE https://tubular-backend.herokuapp.com/exercises/628d56253d6ece3ab378d9e2

### Update an exercise
PUT https://tubular-backend.herokuapp.com/628d505e82b99c3474e6c474 HTTP/1.1
content-type: application/json

{
    "name":"Run Around the Block",
    "description":"Run around the block near our apartment.",
    "images":[],
    "videos":[],
    "tags":["cardio"],
    "user_id": "62871171ad3a5374a92f8aa9"
}

### Delete a profile
DELETE https://tubular-backend.herokuapp.com/profiles/628d4918eac73b481c8f76a7

### Update a profile
PUT https://tubular-backend.herokuapp.com/628d4918eac73b481c8f76a7 HTTP/1.1
content-type: application/json

{
    "userName":"NewerProfile",
    "password":"newProfPass",
    "email":"newProfile@test.com"
}